# Dockerfile for creation of images on the raspberry pi platform (ARM architecture)
FROM arm32v7/maven:3.6.3-adoptopenjdk-11 AS MAVEN_BUILD

COPY ./ ./
ARG FALCON_JDBC_URL=url
ENV FALCON_JDBC_URL=${FALCON_JDBC_URL}
RUN mvn clean package

FROM arm32v7/openjdk:11-jre

COPY --from=MAVEN_BUILD docker/adventurexp-*.jar /adventurexp.jar

CMD ["java", "-jar", "/adventurexp.jar"]
